### ISSUE TITLE
Could be nice to customize the tmpRoot path

### ISSUE THREAD

**Issue by suntehnik** [populov/gradle-save-ssd-plugin#1]
tmpRoot is hardcoded into the Groovy code. Could be nice to customize it as a parameter.

**Comment by populov** [comment]
А можно узнать, какую конкретно проблему это решит (например, конфликты с каким-то конкретным приложением)? 
Или так, просто, чтоб было, на всякий случай?

**Comment by suntehnik** [comment]
Например пользователи windows тоже смогли бы использовать плагин. Под маком
/tmp это симлинк на /private/tmp
 23 мая 2014 г. 18:32 пользователь "Serge Populov" notifications@github.com
написал:

**Comment by populov** [comment]
Я не знаток мака, поэтому спрошу: а чем плохо, что временные файлы де-факто окажутся в /private/tmp ?

Под windows не заработает, т.к. системой не предусмотрен аналог линуксового /tmp (а точнее, tmpfs). Конечно, можно поставить стороннюю приблуду и сделать виртуальный диск в памяти, но, насколько я помню, симлинки можно делать только в пределах одного диска (нельзя сделать симлинк с C: на D:), поэтому на виртуальный диск сослаться не получится.
Так что под виндой:
1. Без пинка не заработает.
2. Даже с пинком не взлетит.

**Comment by suntehnik** [comment]
У вас в захардкожен /tmp. Под маком нет tmpfs и приходится изобретать
костыли. Накладывать точки монтирования после загрузки системы тоже не
совсем хорош:  что-то может перестать работать. Я бы предпочел монтировать
ramfs на другой каталог. Тем более, что реализация будет состоять, как как
я понимаю, из трёх строк.
23 мая 2014 г. 19:05 пользователь "Serge Populov" notifications@github.com
написал:

**Comment by populov** [comment]
Released in 0.2.0:

[+] new option:

**gradle.properties**
saveSSDRoot=/some/path

**Comment by suntehnik** [comment]
Thank you!
